var BaseHandler;

BaseHandler = (function() {
  function BaseHandler(spotify) {
    this.spotify = spotify;
  }

  return BaseHandler;

})();

module.exports = BaseHandler;

// ---
// generated by coffee-script 1.9.2
